[package]
name = "ps1"
version = "1.0.0"
authors = ["Kamil Koczurek <koczurekk@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
whoami = "0.8.1"
colored = "1.9"
dirs = "2.0.2"
anyhow = "1.0"
